name: Update Index for New Directories

on:
  push:
    paths:
      - '**/'  # Trigger the action when any directory is added or changed

jobs:
  update-index:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create a list of directories
      run: |
        # Find all directories (not files), including nested directories
        echo "Listing directories..."        
        find . -type d -not -path '*/\.*' > directories.txt  # Exclude hidden directories (e.g., .git)

    - name: Ensure .nojekyll exists
      run: |
        # Create a .nojekyll file to disable Jekyll processing on GitHub Pages
        if [ ! -f .nojekyll ]; then
          touch .nojekyll
          echo ".nojekyll file created to disable Jekyll"
        fi

    - name: Update index.html
      run: |
        # Read the list of directories from the file
        directories=$(cat directories.txt)

        # Check if index.html exists, and create it if it doesn't
        if [ ! -f index.html ]; then
          echo "<!DOCTYPE html><html><body><h1>Directories</h1><ul>" > index.html
        fi

        # Read the existing directories in the index.html, and store them in current_dirs
        current_dirs=$(grep -oP '(?<=<a href=").*?(?="/>)' index.html || true)

        # Add new directories that are not already in the current index.html
        echo "$directories" | while read dir; do
          # Only add directories (not files), and skip the ones already listed in index.html
          if [ -d "$dir" ] && [[ "$dir" != .* ]] && ! echo "$current_dirs" | grep -q "$dir"; then
            echo "<li><a href=\"$dir/\">$dir</a></li>" >> index.html
          fi
        done

        # Ensure that the closing </ul> and </body></html> are only added once
        if ! grep -q "</ul>" index.html; then
          echo "</ul>" >> index.html
        fi
        if ! grep -q "</body></html>" index.html; then
          echo "</body></html>" >> index.html
        fi

    - name: Commit changes
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add index.html .nojekyll
        git commit -m "Update index.html with new directories and add .nojekyll" || echo "No changes to commit"
        git push
