name: Update Index for New Directories

on:
  push:
    paths:
      - '**/'  # Trigger the action when any directory is added or changed

jobs:
  update-index:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: List directories and update index.html
      run: |
        # Find all directories (including nested ones) in the repository, excluding the current directory
        echo "Listing all directories..."
        directories=$(find . -type d -not -path '*/\.*' -not -path '.')

        # Debugging: print the directories found
        echo "Directories found: $directories"

        # If no directories found, exit
        if [ -z "$directories" ]; then
          echo "No directories found. Exiting."
          exit 0
        fi

        # Check if index.html exists, and create it if it doesn't
        if [ ! -f index.html ]; then
          echo "<!DOCTYPE html><html><body><h1>Directories</h1><ul>" > index.html
        fi

        # Debugging: Print current index.html content
        echo "Current index.html content:"
        cat index.html

        # Add new directories that are not already in the current index.html
        for dir in $directories; do
          # Skip current directory and any hidden directories (e.g., .git)
          if [ -d "$dir" ] && [[ "$dir" != .* ]]; then
            # Debugging: Show the directory being added
            echo "Adding directory: $dir"
            # Ensure proper formatting for href (remove './' if necessary)
            dir_href="${dir#./}"  # Remove leading './' from the directory path
            # Create list items for directories (making sure paths are valid for href)
            echo "<li><a href=\"$dir_href/\">$dir_href</a></li>" >> index.html
          fi
        done

        # Ensure that the closing </ul> and </body></html> tags are only added once
        if ! grep -q "</ul>" index.html; then
          echo "</ul>" >> index.html
        fi
        if ! grep -q "</body></html>" index.html; then
          echo "</body></html>" >> index.html
        fi

    - name: Ensure .nojekyll exists
      run: |
        # Create a .nojekyll file to disable Jekyll processing on GitHub Pages
        if [ ! -f .nojekyll ]; then
          touch .nojekyll
          echo ".nojekyll file created to disable Jekyll"
        fi

    - name: Commit changes
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add index.html .nojekyll
        git commit -m "Update index.html with new directories and add .nojekyll" || echo "No changes to commit"
        git push
