name: Update Index for New Directories

on:
  push:
    paths:
      - '**/'  # Trigger the action when any directory is added or changed

jobs:
  update-index:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create a list of directories
      run: |
        # Find all directories (not files) in the repository
        echo "Listing directories..."        
        find . -type d > directories.txt

    - name: Update index.html
      run: |
        # Read the list of directories from the file
        directories=$(cat directories.txt)

        # Check if index.html exists and create it if it doesn't
        if [ ! -f index.html ]; then
          echo "<!DOCTYPE html><html><body><h1>Directories</h1><ul>" > index.html
        fi

        # Get the current list of directories in index.html (if any)
        current_dirs=$(grep -oP '(?<=<a href=").*?(?="/>)' index.html || true)

        # Append the new directories that aren't already listed in index.html
        echo "$directories" | while read dir; do
          # Add only directories and ignore the ones starting with a dot (hidden directories)
          if [ -d "$dir" ] && [[ "$dir" != .* ]]; then
            # If the directory isn't already listed in index.html, add it
            if ! echo "$current_dirs" | grep -q "$dir"; then
              echo "<li><a href=\"$dir/\">$dir</a></li>" >> index.html
            fi
          fi
        done

        # Close the HTML tags
        echo "</ul></body></html>" >> index.html

    - name: Commit changes
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add index.html
        git commit -m "Update index.html with new directories" || echo "No changes to commit"
        git push
